language: python
python:
  - "2.7"

install:
  - pip install tox

env:
  - TOXENV=flake8
  - TOXENV=py27-django111
  - TOXENV=py3-django2

script:
  - tox $ARGS

deploy:
  provider: pypi
  user: "appsembler"
  password:
    secure: "cvOpGzWDP0jZDvFqhPB0380/XU4FmkFL0275TAM+pFpX8Qj7CZjxqSKvxnKDh0HZfVBAa8vD/WQIB1N8eH5A8ZqjrGdNBSeZfFignjlZEXb3ELD5tliw61YMeyXxh1fhRBGsLDQ3ahnFxAC+EogXY3jZQgsKNuxLx25h3iH+9QZXxncGmgijIW8tKbs0PXGXKkJ6DkK5I5BEKqNe09Q6X533meyA2TsaNlZ5KHkUFOowCwXrxgKgDU6bQKL8kjU3DKjhGK1CuC0/DJAvP73f02ybv1bpoy79DCUzBVyRvT1L/TJMaWbgxMp/p+s8g1c3VS+Uenb7d4MFDQIzPfOVDWapiqbqIV7aOC1zYgpSJ+XeBBfNVX6B7HFZISIGBe7ICm2yvHlW5qOZNwX5j6AeqfLY2x6jknEzaRtyqtB9VyedyxFfSp+FyeO8/YvmCeVbIv+PSVSwSxS7v7lZxBuAEsqRQ3atU9E+ygwhkoIvAJkfTufJOm9G0Qk44kXNikDuUzNmzXYstGVQrdX+tT8xNkTbyNEbGAi5rpD3bpH4ZAcprKNZCv0WJ1egMdh4oUoz/A8aLMpGcVMEiOt6a7to3HxRGi5WPQuPV3RnPlz2u95NGnv0dhpra4AN1l+oq59dRSrCXQ6vmz2HNwPR0Jho9R3UwXmXKcDi4M7K9A+wNvk="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
